#! /usr/bin/env python3
import sys, os
import numpy as np

# This create.parallel.launcher.py creates a launcher file for Lonestar6
# (consumed by LS6's LAUNCHER module, see TACC.LS6.parallel.run.slurm) --
# or, on knox (no LAUNCHER/Slurm there), the same file is run with:
#   nice -n 10 xargs -P $PIE_WORKERS -I{} sh -c '{}' < commands_launcher
# (see README "Large ensemble Monte Carlo simulation").
#
# Each line gets an explicit seed (monteCarlo.run.py argv[1]): the old
# unseeded np.random draw meant no line could be identified, reproduced,
# or safely skipped on a resumed/partial run. sys.executable, not bare
# 'python': the bare python3 on PATH is broken on knox (numpy/pandas ABI
# mismatch; see PATHWAY_FORWARD.md) -- this launcher is meant to be
# generated BY the interpreter that will run the lines, so sys.executable
# here is already the right (pinned venv) one.
total_CPU = 1024
SEED_BASE = int(os.environ.get("PIE_LAUNCHER_SEED_BASE", "20260930"))
with open("commands_launcher", "w") as file:
    for iCPU in range(total_CPU):
        cmd_str = sys.executable + ' monteCarlo.run.py ' + str(SEED_BASE + iCPU) + ' \n'
        file.write(cmd_str)
file.close()
